services:
  prometheus:
    image: prom/prometheus:latest
    container_name: ta-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  alertmanager:
    image: prom/alertmanager:latest
    container_name: ta-alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports:
      - "9093:9093"

  redis:
    image: "redis:7.2"
    container_name: ta-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  temp-alert:
    build:
      context:
        ..
      # args:
      #   TA_BASE_PATH: /temp-alert

    container_name: temp-alert
    ports:
      - "4000:4000"
    environment:
      # yeah it's just for development no worries
      TA_SECRET_KEY_BASE: yNzhTd/NjNSCeo9bGt/073Dj0ut/t87kfQ0jTddrtoeiB7MObdYo/AdpaiKS0xCl
      TA_ALERTMANAGER_URL: http://alertmanager:9093/
      TA_STORAGE_BACKEND: file
      # TA_REDIS_HOST: redis
      TA_FILE_STORAGE_PATH: /temp-alert-data
    volumes:
      - temp_alert_data:/temp-alert-data

volumes:
  redis_data:
  temp_alert_data:
