name: Docker Image CI

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract version tag
      id: extract_tag
      run: |
        if [ "${{ github.ref_type }}" = "tag" ]; then
          # Remove the 'v' prefix if it exists
          TAG=${GITHUB_REF#refs/tags/}
          TAG=${TAG#v}
          echo "TAG=$TAG" >> $GITHUB_ENV
        else
          echo "TAG=latest" >> $GITHUB_ENV
        fi

    - name: Build and tag Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/temp-alert:${{ env.TAG }}

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/temp-alert:${{ env.TAG }}
